pipeline {
    agent {label 'k8s-pod'}
    stages {
        stage('Build') {
            steps {
                sh '''
                    #!/bin/bash
                    export PATH=/opt/apache-maven-3.9.5/bin:$PATH
                    mvn --version
                    mvn -B -DskipTests clean package
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    #!/bin/bash
                    export PATH=/opt/apache-maven-3.9.5/bin:$PATH
                    mvn --version
                    mvn test
                 '''
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy to Nexus') {
            steps {
                sh '''
                    #!/bin/bash
                    export PATH=/opt/apache-maven-3.9.5/bin:$PATH
                    ls -al /opt/apache-maven-3.9.5/
                    cp ./nexus/settings.xml /opt/apache-maven-3.9.5/conf
                    mvn --version
                    mvn deploy
                '''
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Multi-brnch-1') {
            steps {
                echo "Only saw in branch:multi-branch-test1"
            }
        }
    }
}
