pipeline {
    agent {label 'k8s-pod'}
    stages {
        stage('Build') {
            steps {
                sh '''
                    export PATH=/opt/apache-maven-3.9.5/bin:$PATH
                    mvn --version
                    mvn -B -DskipTests clean package'
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    #!/bin/bash
                    export PATH=/opt/apache-maven-3.9.5/bin:$PATH
                    mvn --version
                    mvn test
                 '''
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
