pipeline {
    agent {label 'k8s-pod'}
    stages {
        stage('Build') {
            steps {
                sh '''
                    #!/bin/bash
                    export PATH=/opt/apache-maven-3.9.5/bin:$PATH
                    mvn --version
                    mvn -B -DskipTests clean package
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    #!/bin/bash
                    export PATH=/opt/apache-maven-3.9.5/bin:$PATH
                    mvn --version
                    mvn test
                 '''
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy to Nexus') {
            steps {
                configFileProvider(
                    [configFile(fileId: 'nexus3', variable: 'MAVEN_SETTINGS')]) {
                    // sh 'mvn -s $MAVEN_SETTINGS package --batch-mode'
                    sh 'mvn -s $MAVEN_SETTINGS clean deploy -X'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Multi-brnch-1') {
            steps {
                echo "Only saw in branch:multi-branch-test1"
            }
        }
    }
}
